package stopwords_list


var StopWords = map[string]bool{
	"a": true, "abord": true, "about": true, "above": true, "absolument": true, "afin": true, "after": true, "again": true,
	"against": true, "ah": true, "ai": true, "aie": true, "aient": true, "aies": true, "ailleurs": true, "ainsi": true,
	"ait": true, "all": true, "allaient": true, "allo": true, "allons": true, "allô": true, "alors": true, "am": true,
	"an": true, "and": true, "anterieur": true, "anterieure": true, "anterieures": true, "any": true, "apres": true, "après": true,
	"are": true, "as": true, "assez": true, "at": true, "attendu": true, "au": true, "aucun": true, "aucune": true,
	"aucuns": true, "aujourd": true, "aujourd'hui": true, "aupres": true, "auquel": true, "aura": true, "aurai": true,
	"auraient": true, "aurais": true, "aurait": true, "auras": true, "aurez": true, "auriez": true, "aurions": true,
	"aurons": true, "auront": true, "aussi": true, "autant": true, "autre": true, "autrefois": true, "autrement": true,
	"autres": true, "autrui": true, "aux": true, "auxquelles": true, "auxquels": true, "avaient": true, "avais": true,
	"avait": true, "avant": true, "avec": true, "avez": true, "aviez": true, "avions": true, "avoir": true, "avons": true,
	"ayant": true, "ayez": true, "ayons": true, "b": true, "bah": true, "bas": true, "basee": true, "bat": true,
	"be": true, "beau": true, "beaucoup": true, "because": true, "been": true, "before": true, "being": true, "below": true,
	"between": true, "bien": true, "bigre": true, "bon": true, "both": true, "boum": true, "bravo": true, "brrr": true,
	"but": true, "by": true, "c": true, "can": true, "car": true, "ce": true, "ceci": true, "cela": true, "celle": true,
	"celle-ci": true, "celle-là": true, "celles": true, "celles-ci": true, "celles-là": true, "celui": true, "celui-ci": true,
	"celui-là": true, "celà": true, "cent": true, "cependant": true, "certain": true, "certaine": true, "certaines": true,
	"certains": true, "certes": true, "ces": true, "cet": true, "cette": true, "ceux": true, "ceux-ci": true, "ceux-là": true,
	"chacun": true, "chacune": true, "chaque": true, "cher": true, "chers": true, "chez": true, "chiche": true, "chut": true,
	"chère": true, "chères": true, "ci": true, "cinq": true, "cinquantaine": true, "cinquante": true, "cinquantième": true,
	"cinquième": true, "clac": true, "clic": true, "combien": true, "comme": true, "comment": true, "comparable": true,
	"comparables": true, "compris": true, "concernant": true, "contre": true, "couic": true, "crac": true, "d": true,
	"da": true, "dans": true, "de": true, "debout": true, "dedans": true, "dehors": true, "deja": true, "delà": true,
	"depuis": true, "dernier": true, "derniere": true, "derriere": true, "derrière": true, "des": true, "desormais": true,
	"desquelles": true, "desquels": true, "dessous": true, "dessus": true, "deux": true, "deuxième": true, "deuxièmement": true,
	"devant": true, "devers": true, "devra": true, "devrait": true, "did": true, "different": true, "differentes": true,
	"differents": true, "différent": true, "différente": true, "différentes": true, "différents": true, "dire": true,
	"directe": true, "directement": true, "dit": true, "dite": true, "dits": true, "divers": true, "diverse": true,
	"diverses": true, "dix": true, "dix-huit": true, "dix-neuf": true, "dix-sept": true, "dixième": true, "do": true,
	"does": true, "doing": true, "doit": true, "doivent": true, "don": true, "donc": true, "dont": true, "dos": true,
	"douze": true, "douzième": true, "down": true, "dring": true, "droite": true, "du": true, "duquel": true, "durant": true,
	"during": true, "dès": true, "début": true, "désormais": true, "e": true, "each": true, "effet": true, "egale": true,
	"egalement": true, "egales": true, "eh": true, "elle": true, "elle-même": true, "elles": true, "elles-mêmes": true,
	"en": true, "encore": true, "enfin": true, "entre": true, "envers": true, "environ": true, "es": true, "essai": true,
	"est": true, "et": true, "etant": true, "etc": true, "etre": true, "eu": true, "eue": true, "eues": true, "euh": true,
	"eurent": true, "eus": true, "eusse": true, "eussent": true, "eusses": true, "eussiez": true, "eussions": true,
	"eut": true, "eux": true, "eux-mêmes": true, "exactement": true, "excepté": true, "extenso": true, "exterieur": true,
	"eûmes": true, "eût": true, "eûtes": true, "f": true, "fais": true, "faisaient": true, "faisant": true, "fait": true,
	"faites": true, "façon": true, "feront": true, "few": true, "fi": true, "flac": true, "floc": true, "fois": true,
	"font": true, "for": true, "force": true, "from": true, "furent": true, "further": true, "fus": true, "fusse": true,
	"fussent": true, "fusses": true, "fussiez": true, "fussions": true, "fut": true, "fûmes": true, "fût": true,
	"fûtes": true, "g": true, "gens": true, "h": true, "ha": true, "had": true, "has": true, "haut": true, "have": true,
	"having": true, "he": true, "hein": true, "hem": true, "hep": true, "her": true, "here": true, "hers": true,
	"herself": true, "hi": true, "him": true, "himself": true, "his": true, "ho": true, "holà": true, "hop": true,
	"hormis": true, "hors": true, "hou": true, "houp": true, "how": true, "hue": true, "hui": true, "huit": true,
	"huitième": true, "hum": true, "hurrah": true, "hé": true, "hélas": true, "i": true, "ici": true, "if": true,
	"il": true, "ils": true, "importe": true, "in": true, "into": true, "is": true, "it": true, "its": true,
	"itself": true, "j": true, "je": true, "jusqu": true, "jusque": true, "just": true, "juste": true, "k": true,
	"l": true, "la": true, "laisser": true, "laquelle": true, "las": true, "le": true, "lequel": true, "les": true,
	"lesquelles": true, "lesquels": true, "leur": true, "leurs": true, "longtemps": true, "lors": true, "lorsque": true,
	"lui": true, "lui-meme": true, "lui-même": true, "là": true, "lès": true, "m": true, "ma": true, "maint": true,
	"maintenant": true, "mais": true, "malgre": true, "malgré": true, "maximale": true, "me": true, "meme": true,
	"memes": true, "merci": true, "mes": true, "mien": true, "mienne": true, "miennes": true, "miens": true, "mille": true,
	"mince": true, "mine": true, "minimale": true, "moi": true, "moi-meme": true, "moi-même": true, "moindres": true,
	"moins": true, "mon": true, "more": true, "most": true, "mot": true, "moyennant": true, "multiple": true,
	"multiples": true, "my": true, "myself": true, "même": true, "mêmes": true, "n": true, "na": true, "naturel": true,
	"naturelle": true, "naturelles": true, "ne": true, "neanmoins": true, "necessaire": true, "necessairement": true,
	"neuf": true, "neuvième": true, "ni": true, "no": true, "nombreuses": true, "nombreux": true, "nommés": true,
	"non": true, "nor": true, "nos": true, "not": true, "notamment": true, "notre": true, "nous": true, "nous-mêmes": true,
	"nouveau": true, "nouveaux": true, "now": true, "nul": true, "néanmoins": true, "nôtre": true, "nôtres": true,
	"o": true, "of": true, "off": true, "oh": true, "ohé": true, "ollé": true, "olé": true, "on": true, "once": true,
	"only": true, "ont": true, "onze": true, "onzième": true, "or": true, "ore": true, "other": true, "ou": true,
	"ouf": true, "ouias": true, "our": true, "ours": true, "ourselves": true, "oust": true, "ouste": true, "out": true,
	"outre": true, "ouvert": true, "ouverte": true, "ouverts": true, "over": true, "own": true, "o|": true, "où": true,
	"p": true, "paf": true, "pan": true, "par": true, "parce": true, "parfois": true, "parle": true, "parlent": true,
	"parler": true, "parmi": true, "parole": true, "parseme": true, "partant": true, "particulier": true, "particulière": true,
	"particulièrement": true, "pas": true, "passé": true, "pendant": true, "pense": true, "permet": true, "personne": true,
	"personnes": true, "peu": true, "peut": true, "peuvent": true, "peux": true, "pff": true, "pfft": true, "pfut": true,
	"pif": true, "pire": true, "pièce": true, "plein": true, "plouf": true, "plupart": true, "plus": true, "plusieurs": true,
	"plutôt": true, "possessif": true, "possessifs": true, "possible": true, "possibles": true, "pouah": true, "pour": true,
	"pourquoi": true, "pourrais": true, "pourrait": true, "pouvait": true, "prealable": true, "precisement": true,
	"premier": true, "première": true, "premièrement": true, "pres": true, "probable": true, "probante": true,
	"procedant": true, "proche": true, "près": true, "psitt": true, "pu": true, "puis": true, "puisque": true,
	"pur": true, "pure": true, "q": true, "qu": true, "quand": true, "quant": true, "quant-à-soi": true, "quanta": true,
	"quarante": true, "quatorze": true, "quatre": true, "quatre-vingt": true, "quatrième": true, "quatrièmement": true,
	"que": true, "quel": true, "quelconque": true, "quelle": true, "quelles": true, "quelqu'un": true, "quelque": true,
	"quelques": true, "quels": true, "qui": true, "quiconque": true, "quinze": true, "quoi": true, "quoique": true,
	"r": true, "rare": true, "rarement": true, "rares": true, "relative": true, "relativement": true, "remarquable": true,
	"rend": true, "rendre": true, "restant": true, "reste": true, "restent": true, "restrictif": true, "retour": true,
	"revoici": true, "revoilà": true, "rien": true, "s": true, "sa": true, "sacrebleu": true, "sait": true, "same": true,
	"sans": true, "sapristi": true, "sauf": true, "se": true, "sein": true, "seize": true, "selon": true, "semblable": true,
	"semblaient": true, "semble": true, "semblent": true, "sent": true, "sept": true, "septième": true, "sera": true,
	"serai": true, "seraient": true, "serais": true, "serait": true, "seras": true, "serez": true, "seriez": true,
	"serions": true, "serons": true, "seront": true, "ses": true, "seul": true, "seule": true, "seulement": true,
	"she": true, "should": true, "si": true, "sien": true, "sienne": true, "siennes": true, "siens": true, "sinon": true,
	"six": true, "sixième": true, "so": true, "soi": true, "soi-même": true, "soient": true, "sois": true, "soit": true,
	"soixante": true, "some": true, "sommes": true, "son": true, "sont": true, "sous": true, "souvent": true, "soyez": true,
	"soyons": true, "specifique": true, "specifiques": true, "speculatif": true, "stop": true, "strictement": true,
	"subtiles": true, "such": true, "suffisant": true, "suffisante": true, "suffit": true, "suis": true, "suit": true,
	"suivant": true, "suivante": true, "suivantes": true, "suivants": true, "suivre": true, "sujet": true, "superpose": true,
	"sur": true, "surtout": true, "t": true, "ta": true, "tac": true, "tandis": true, "tant": true, "tardive": true,
	"te": true, "tel": true, "telle": true, "tellement": true, "telles": true, "tels": true, "tenant": true, "tend": true,
	"tenir": true, "tente": true, "tes": true, "than": true, "that": true, "the": true, "their": true, "theirs": true,
	"them": true, "themselves": true, "then": true, "there": true, "these": true, "they": true, "this": true,
	"those": true, "through": true, "tic": true, "tien": true, "tienne": true, "tiennes": true, "tiens": true, "to": true,
	"toc": true, "toi": true, "toi-même": true, "ton": true, "too": true, "touchant": true, "toujours": true, "tous": true,
	"tout": true, "toute": true, "toutefois": true, "toutes": true, "treize": true, "trente": true, "tres": true,
	"trois": true, "troisième": true, "troisièmement": true, "trop": true, "très": true, "tsoin": true, "tsouin": true,
	"tu": true, "té": true, "u": true, "un": true, "under": true, "une": true, "unes": true, "uniformement": true,
	"unique": true, "uniques": true, "uns": true, "until": true, "up": true, "v": true, "va": true, "vais": true,
	"valeur": true, "vas": true, "vers": true, "very": true, "via": true, "vif": true, "vifs": true, "vingt": true,
	"vivat": true, "vive": true, "vives": true, "vlan": true, "voici": true, "voie": true, "voient": true, "voilà": true,
	"voire": true, "vont": true, "vos": true, "votre": true, "vous": true, "vous-mêmes": true, "vu": true, "vé": true,
	"vôtre": true, "vôtres": true, "w": true, "was": true, "we": true, "were": true, "what": true, "when": true,
	"where": true, "which": true, "while": true, "who": true, "whom": true, "why": true, "will": true, "with": true,
	"x": true, "y": true, "you": true, "your": true, "yours": true, "yourself": true, "yourselves": true, "z": true,
	"zut": true, "à": true, "â": true, "ça": true, "ès": true, "étaient": true, "étais": true, "était": true,
	"étant": true, "état": true, "étiez": true, "étions": true, "été": true, "étée": true, "étées": true, "étés": true,
	"etes": true, "être": true, "ô": true,
}
